### PR TITLE
ParlaMint-AT

### PR DESCRIPTION
**Pull request by hpreki**
First attempt for ParlaMint-AT Sample Data

Apart from the content  submitted in `Data/ParlaMint-AT` this pull-request only has the following "global" changes: 

* .gitignore : added a few exceptions for AT-data
* Script/ : I think that at one point I made a  change from `python` to `python3`

### CODE REVIEW

**Comment by matyaskopp** [comment]
@hpreki, nice work. I will review it tomorrow.

meanwhile, please remove unused taxonomies: `m/ParlaMint-AT-taxonomy-.*\.xml/`

I was sure that my validation was ok, but it took me five difficult minutes to determine how you have been able to hack my validation with obviously invalid data (wrong id and missing lang):

```XML
<?xml version="1.0" encoding="UTF-8"?>
<taxonomy xmlns="http://www.tei-c.org/ns/1.0" xml:id="NER">
    <desc>
        <term>Named entities</term>
    </desc>
```
Nice attempt to make me think that I am mad :-)

@TomazErjavec, we should probably extend validation and check that the folder does not contain a mess (= every XML is included in some root file)

**Comment by hpreki** [comment]
I now replaced the .xml files by their full-sized originals. For now I left out  any of the changes mentioned 
in #453

**Comment by matyaskopp** [comment]
great, You have just discovered one bug:
1. I am detecting 'error' in the log to determine whether it fails. This warning:
https://github.com/clarin-eric/ParlaMint/actions/runs/3445671964/jobs/5749669962#step:4:633
```
WARN ParlaMint-AT_2022-04-27-027_XXVII_NRSITZ_00153: Trailing space in seg: 
             , Frau Präsidentin –: Wenn Herr Vilimsky hier von Kriegstreibern spricht, also Leute, die sich bei Putin, der damals schon ein Kriegsverbrecher war – ich verweise auf Grosny –, ein Terrorist war – ich verweise auf die Anschläge in Moskau –, der jetzt davon redet ...
```
contains word T**error**ist

I will update your repository - it is [45 commits behind](https://github.com/hpreki/ParlaMint/compare/data...clarin-eric:ParlaMint:data), so the 67f0756ebf016f2b434bd50b4131921fdbbd777d will be used

**Comment by matyaskopp** [comment]
@TomazErjavec this:
https://github.com/clarin-eric/ParlaMint/actions/runs/3445838578/jobs/5750028600#step:4:1210
image

is related to your change #439

**Comment by TomazErjavec** [comment]
Ah, this was the testing I was referring to. Where can I get the AT data?

**Comment by TomazErjavec** [comment]
Never mind, found it.

**Comment by TomazErjavec** [comment]
Fixed, I hope.

**Comment by matyaskopp** [comment]
> I am detecting 'error' in the log to determine whether it fails. This warning: https://github.com/clarin-eric/ParlaMint/actions/runs/3445671964/jobs/5749669962#step:4:633
> 
> ```
> WARN ParlaMint-AT_2022-04-27-027_XXVII_NRSITZ_00153: Trailing space in seg: 
>              , Frau Präsidentin –: Wenn Herr Vilimsky hier von Kriegstreibern spricht, also Leute, die sich bei Putin, der damals schon ein Kriegsverbrecher war – ich verweise auf Grosny –, ein Terrorist war – ich verweise auf die Anschläge in Moskau –, der jetzt davon redet ...
> ```
> 
> contains word T**error**ist

fixed:
image

**Pull request merged**
