### PR TITLE
data BG

### PR DESCRIPTION
**Pull request by matyaskopp**

### CODE REVIEW

**Comment by matyaskopp** [comment]
@ivo-clark, I have made a pull request for you

**Comment by ivo-clark** [comment]
@matyaskopp Can you check the latest commit of "Initial BG sample"? I think we managed to fix all issues.

**Comment by matyaskopp** [comment]
> @matyaskopp Can you check the latest commit of "Initial BG sample"? I think we managed to fix all issues.

@ivo-clark, I don't think so. You can see the validation log here: https://github.com/clarin-eric/ParlaMint/actions/runs/3541555651/jobs/5945978308#step:4:26

**Comment by ivo-clark** [comment]
@matyaskopp We are ready with the initial commit, can you please check and merge it?

**Comment by ivo-clark** [comment]
@matyaskopp Hi I have updated the local branch, can you please merge it?

**Pull request merged**
