### PR TITLE
Data-HR sample

### PR DESCRIPTION
**Pull request by 5roop**
Sample of HR data.

Current prime minister was added manually so that the data validates. For the whole collection we won't be adding them as discussed in #398.

### CODE REVIEW

**Comment by matyaskopp** [comment]
@5roop I guess that HR data are in [5roop:data_hr](https://github.com/5roop/ParlaMint/tree/data_hr) branch, not in [5roop:data](https://github.com/5roop/ParlaMint/tree/data), so this pull request should be replaced with:
https://github.com/clarin-eric/ParlaMint/compare/data...5roop:ParlaMint:data_hr

**Comment by 5roop** [comment]
Yes, I started with local branch data as per contributing guidelines, but I soon realized this won't work for submitting 3 corpora. Please advise on next steps, should I close it and create a new PR?

**Comment by matyaskopp** [comment]
> Yes, I started with local branch data as per contributing guidelines, but I soon realized this won't work for submitting 3 corpora. Please advise on next steps, should I close it and create a new PR?

yes, it would be best.
and you can also remove [5roop:data](https://github.com/5roop/ParlaMint/tree/data) branch to avoid confusion.

**Comment by 5roop** [comment]
Closed and opened #559.

**Pull request closed without merging**
