### PR TITLE
Data Validation - GB

### PR DESCRIPTION
**Pull request by amandanwadkwe**

### CODE REVIEW

**Comment by TomazErjavec** [comment]
@amandanwadkwe, looks like you will need to make a smaller sample. Pls. also accept invitation to ParlaMint, so issues can be assigned to you.

**Comment by amandanwadkwe** [comment]
Thank you @TomazErjavec I will do that now

**Comment by amandanwadkwe** [comment]
Do I close a pull request and create a new one please?

**Comment by TomazErjavec** [comment]
> Do I close a pull request and create a new one please?

This I leave to @matyaskopp, he is the master of pull requests.

**Comment by matyaskopp** [comment]
> Do I close a pull request and create a new one please?

No, just update your fork

**Comment by amandanwadkwe** [comment]
Thank you

**Pull request closed without merging**
