### PR TITLE
Data fixings v2tov3

### PR DESCRIPTION
**Pull request by matyaskopp**

### CODE REVIEW

**Comment by TomazErjavec** [comment]
OK, I can also run it country by country:
- CZ, DK, FR same problem as BG (`affiliation/@role=chairman`), should be president
- GB, similar problem (`affiliation/@role=speaker`), should be president
- SI has
```
<org xml:id="party.NeP" role="independent">
  <orgName full="yes" xml:lang="sl">Nepovezani poslanci</orgName>
  <orgName full="yes" xml:lang="en">Unrelated members of parliament</orgName>  
  <orgName full="init">NeP</orgName>
 </org>
 ```
This one should now of course be `org/@role="parliamentaryGroup"`. I assume this can also be fix automatically.

And the other corpora are ok. Becaus etehre are many errors of the type above, there might be some more problems, but I think not.

**Comment by matyaskopp** [comment]
@TomazErjavec I have fixed the `chairman`-role issue for the obligatory organizations.
I am not sure what was the decision for the voluntary organizations. Should affiliation with them also be fixed?

**Comment by TomazErjavec** [comment]
> I am not sure what was the decision for the voluntary organizations. Should affiliation with them also be fixed?
Yes, because "chairman" (and, shortly, "chairperson") do not exist anymore as valid roles. Should be changed to "president". We now have this error in CZ:
```
<affiliation ref="#subcommittee.PEFPS.1414"
role="chairman"
from="2018-03-14T00:00:00"
to="2021-10-21T00:00:00"/>
```

**Comment by matyaskopp** [comment]
`speaker` should be changed to `president` in both CZ and GB cases.
`president` role means that the person is the big boss.

The idea is to have one common role for all "big bosses": speaker in parliament, prime minister in the government, leader in a political party, etc...
We have to discuss where we will store local names and their translations - Now, I don't see any straightforward solution.

**Comment by TomazErjavec** [comment]
> That'll be very confusing for any UK parliament users. They are not presidents in any shape or form.

This decission is - or so it seems to us, incl. some specialists in parl. studies - the least evil choice. Because we do want interoperability among the parliaments, and  "speaker", "peer", and, to an extent, "MP" are confusing, or even completely wrong for non-UK parliaments. 

You can look at it as an abstract label - it doesn't mean that it has to be displayed in this form e.g. in the concordancer.
However, as we are changing things around now, if you have a better cover term for president, prime minister, chairperson, and speaker, pls. let us know.

**Comment by matyaskopp** [comment]
> Also, is there any target that validates against the TEI ODD schema? Or maybe the standard validation could also validate against ParlaMint/TEI/ParlaMint.rng ?

@TomazErjavec 
I have added target that validates with `ParlaMint/TEI/ParlaMint.rng`. (it is now merged with documentation [5f51018](https://github.com/clarin-eric/ParlaMint/commit/5f51018318793508d6731f01183488dcc93fa787))
```bash
make DEV-val-schema-ParlaMintODD
```
or 
```bash
make DEV-val-schema-ParlaMintODD-XX
```
for `XX` country

**Comment by TomazErjavec** [comment]
@perayson, we continue the discussion on affiliation roles in a dedicated issue for this: #245.

**Comment by matyaskopp** [comment]
> GR: they also have two organisations with "independent" roles, which are now no longer supported:
ParlaMint/Data/ParlaMint-GR/ParlaMint-GR.xml
https://github.com/clarin-eric/ParlaMint/blob/6b7fcd5ca234bfb56ab83679b697ace5c5e0148e/Data/ParlaMint-GR/ParlaMint-GR.xml#L410-L419
I think the situation here is the same as SI, namely that party.ΑΝΕΞΑΡΤΗΤΟΙ_ΕΚΤΟΣ_ΚΟΜΜΑΤΟΣ should be removed and the persons affiliations with it deleted, while party.ΕΞΩΚΟΙΝΟΒΟΥΛΕΥΤΙΚΟΣ role should be renamed to parliamentaryGroup.

agree: `party.ΑΝΕΞΑΡΤΗΤΟΙ_ΕΚΤΟΣ_ΚΟΜΜΑΤΟΣ` should be removed.

don't agree: `party.ΕΞΩΚΟΙΝΟΒΟΥΛΕΥΤΙΚΟΣ` with changing role to `parliamentaryGroup`. I think that this group is not related to parliament because the members of this group are not MP. Two proofs:
 - MP role is not in original data
 - translation from greek 
image


I believe that only the member of parliament can be a member of parliamentary group. So my guess is that  `party.ΕΞΩΚΟΙΝΟΒΟΥΛΕΥΤΙΚΟΣ` should be removed too.


> HU: this is an old error: <name type="adress">Kossuth tér 1-3.</name>, i.e. "adress" should be changed to 'address'. Maybe you can just fix it in v2tov3 script and we can then also close https://github.com/clarin-eric/ParlaMint/issues/172.
SI: still has the "independent" error, so https://github.com/clarin-eric/ParlaMint/issues/243

I will fix it

**Pull request closed without merging**
