### PR TITLE
BG: taxonomies translation

### PR DESCRIPTION
**Pull request by matyaskopp**

### CODE REVIEW

**Comment by matyaskopp** [comment]
@osenova, have you finished these translations? Can I merge them into the ParlaMint repository?

**Comment by osenova** [comment]
Hi, the ones I committed are ready. I have some more on the way.

**Comment by matyaskopp** [comment]
> Hi, the ones I committed are ready. I have some more on the way.

ok, great, let me know when your taxonomies are ready. I will then merge it.

**Comment by osenova** [comment]
Hi Matyas, 

I translated everything except UD but there were no elements in BG. So, if this was the task, I seem to be ready. :)

**Pull request merged**
