### PR TITLE
fix data-IT with v2tov3

### PR DESCRIPTION
**Pull request by matyaskopp**

### CODE REVIEW

**Comment by atomm** [comment]
is the data committed in the data-IT branch "v2tov3 converted" or is it a sample of the old v2 corpus? 
I'm asking because I obtain a slightly different error log applying make validate-parlamint-IT on the data-IT branch data compared to the above log of the github actions.

**Comment by atomm** [comment]
also, I will need to reconstruct the v2tov3 conversion since I will need to implement it in the code to convert from sources and run it both on the "old" sources and on the new sources covering up to june 2022. Any hint on how to quickly spot the differences between v2 and v3 to implement them in my conversion code?

**Comment by atomm** [comment]
> I will need to reconstruct the v2tov3 conversion since I will need to implement it in the code to convert from sources and run it both on the "old" sources and on the new sources covering up to june 2022. Any hint on how to quickly spot the differences between v2 and v3 to implement them in my conversion code?

I guess the "v2tov3" fixes can be found by inspecting the transformations applied by v2tov3.pl

**Comment by matyaskopp** [comment]
The fixings are done with `make fix-v2tov3-full-IT` on current sample data in `data` branch.

**Comment by matyaskopp** [comment]
> ... Any hint on how to quickly spot the differences between v2 and v3 to implement them in my conversion code?

_@atomm, I am back in civilization, I can extend my answer._

I have placed the answer in this issue: #300 

So for your issue, you can use:
```bash
git difftool -t meld --dir-diff data data-IT
```

**Comment by atomm** [comment]
2. Why is Role ‘secretary’ not allowed with parliamentary group organization? 

WARN[17] ParlaMint-IT: Invalid role 'secretary' - unexpected affiliation role with parliamentary group organization..

see e.g. https://www.senato.it/leg/18/BGT/Schede/Attsen/00029282.htm 

Gruppo Partito Democratico : 
 Membro dal 27 marzo 2018 al 1 maggio 2018  
**Segretario** dal 2 maggio 2018 al 24 marzo 2021  
Membro dal 25 marzo 2021


      <xsl:when test="$orgrole = 'parliamentaryGroup' and not(contains(' head deputyHead member ', mk:borders($role)))">17:WARN)unexpected affiliation role with parliamentary group organization</xsl:when>

**Comment by matyaskopp** [comment]
> Why is Role ‘primeMinister’ not allowed?
> `ERROR[14] ParlaMint-IT: Invalid role 'primeMinister' - not allowed in any…`

We have decided to use the `head` role for every "big boss" person affiliation. So for every organization, the main person should be affiliated with the `head` role.
You can encode the `prime minister` role this way if you want to preserve familiar naming:
```XML
                  <affiliation role="head"
                               ref="#GOV"
                               from="2018-06-01"
                               to="2019-09-04"
                               ana="#GOV.CONTE.1">
                     <roleName xml:lang="en">Prime Minister</roleName>
                     <roleName xml:lang="it">Primo ministro</roleName>
                  </affiliation>
```

**Comment by atomm** [comment]
> > Why is Role ‘primeMinister’ not allowed?
> > `ERROR[14] ParlaMint-IT: Invalid role 'primeMinister' - not allowed in any…`
> 
> We have decided to use the `head` role for every "big boss" person affiliation. So for every organization, the main person should be affiliated with the `head` role. You can encode the `prime minister` role this way if you want to preserve familiar naming:
> 
> ```
>                 

> ```

OK. 

Would  it be more precisely like: 


<affiliation ana="#GOV.CONTE.1"
                               from="2018-06-01"
                               ref="#GOV"
                               role="head"
                               role="member"
                               to="2019-09-04">
                     <roleName xml:lang="en">President of the Council of Ministers</roleName>
                     <roleName xml:lang="it">Presidente del Consiglio dei Ministri</roleName>
  </affiliation>
 

in order to prevent ERROR[18] ParlaMint-IT: Missing implicated affiliation role 'member'   ?

**Comment by atomm** [comment]
> > Why is Role ‘primeMinister’ not allowed?
> > `ERROR[14] ParlaMint-IT: Invalid role 'primeMinister' - not allowed in any…`
> 
> We have decided to use the `head` role for every "big boss" person affiliation. So for every organization, the main person should be affiliated with the `head` role. You can encode the `prime minister` role this way if you want to preserve familiar naming:
> 
> ```
>                   <affiliation role="head"
>                                ref="#GOV"
>                                from="2018-06-01"
>                                to="2019-09-04"
>                                ana="#GOV.CONTE.1">
>                      <roleName xml:lang="en">Prime Minister</roleName>
>                      <roleName xml:lang="it">Primo ministro</roleName>
>                   </affiliation>
> ```

Fine. And how would I fix 

ERROR[18] ParlaMint-IT: Missing implicated affiliation role 'member'

for such case (and any other cases)? 

Is it by duplicating the affiliation node with role "member" or by adding  the value "member" to the role attribute of the same affiliation?

**Comment by TomazErjavec** [comment]
> Is it by duplicating the affiliation node with role "member" 

Yes, exactly.

I should note that we also try to document these encoding decisions in the guidelines, in this case cf. the [Section on Speaker affiliations](https://clarin-eric.github.io/ParlaMint/#sec-affiliation). If the guidelines are incorrect, confusing or not explicit enough, we'd be glad to hear about it. (Actually I just noticed a few typos in this section, will fix them).

**Comment by TomazErjavec** [comment]
@matyaskopp `ERROR[18] ParlaMint-IT: Missing implicated affiliation role 'member'` would be better formulated as `ERROR[18] ParlaMint-IT: Missing implied affiliation role 'member'`

**Comment by atomm** [comment]
Hi, could you explain me this test on fix-overlapping-affiliations.xsl
```
  <xsl:function name="mk:get_from">
    <xsl:param name="node"/>
    <xsl:choose>
      <xsl:when test="$node/@from"><xsl:value-of select="$node/@from"/></xsl:when>
      <xsl:when test="$node/@when"><xsl:value-of select="$node/@from"/></xsl:when>
      <xsl:when test="$node
                        and $node/ancestor::tei:teiHeader//tei:sourceDesc/tei:bibl[1]/tei:date
                        and not($node/parent::tei:bibl/parent::tei:sourceDesc/parent::tei:fileDesc)">
        <xsl:value-of select="mk:get_from($node/ancestor::tei:teiHeader//tei:sourceDesc/tei:bibl[1]/tei:date)"/>
      </xsl:when>
      <xsl:otherwise>1500-01-01</xsl:otherwise>
    </xsl:choose>
  </xsl:function>
```

rising warnings like the following: 

WARN[01] ParlaMint-IT: affiliation collision: (2018-03-27 --- 2018-07-03) has one day overlap with (1500-01-01 --- ) affiliation (line:) deputyHead-#group.M5S.2
WARN[01] ParlaMint-IT: affiliation collision: (2018-03-27 --- 2018-07-03) has one day overlap with (1500-01-01 --- ) affiliation (line:) member-#group.M5S.2
WARN[01] ParlaMint-IT: affiliation collision: (2018-07-03 --- 2020-11-18) has one day overlap with (1500-01-01 --- ) affiliation (line:) member-#group.M5S.2
WARN[01] ParlaMint-IT: affiliation collision: (2015-04-22 --- 2015-11-02) has one day overlap with (1500-01-01 --- ) affiliation (line:) member-#group.M5S.1
WARN[01] ParlaMint-IT: affiliation collision: (2014-10-16 --- 2015-04-22) has one day overlap with (1500-01-01 --- ) affiliation (line:) member-#group.M5S.1
WARN[01] ParlaMint-IT: affiliation collision: (2015-07-24 --- 2016-02-02) has one day overlap with (1500-01-01 --- ) affiliation (line:) member-#group.M5S.1


and how could I get rid of them ?

**Comment by matyaskopp** [comment]
It is just a warning - so there is no need to fix it. I have to admit that there is a bug in the validation script, so it does not show the correct date ranges. This line:
```
WARN[01] ParlaMint-IT: affiliation collision: (2018-03-27 --- 2018-07-03) has one day overlap with (1500-01-01 --- ) affiliation (line:) deputyHead-#group.M5S.2
```
is reported by:
https://github.com/clarin-eric/ParlaMint/blob/ba3d7c1a13a53036826753f4dd4387294e21b926/Scripts/validate-parlamint-particDesc.xsl#L49-L53
https://github.com/clarin-eric/ParlaMint/blob/ba3d7c1a13a53036826753f4dd4387294e21b926/Scripts/validate-parlamint-particDesc.xsl#L73-L80

and corresponds to `#PerilliGianluca` affiliations:
```XML
               <person xml:id="PerilliGianluca">
                  <persName>
                     <surname>Perilli</surname>
                     <forename>Gianluca</forename>
                  </persName>
                  ...
                  <affiliation ana="#LEG.18"
                               from="2018-03-27"
                               ref="#group.M5S.2"
                               role="deputyHead"
                               to="2018-07-03">
                     <roleName xml:lang="en">Vice President</roleName>
                  </affiliation>
                  ...
                  <affiliation ana="#LEG.18"
                               from="2018-07-03"
                               ref="#group.M5S.2"
                               role="deputyHead"
                               to="2019-10-16">
                     <roleName xml:lang="en">Vice President</roleName>
                  </affiliation>
               </person>
```
there is a one-day overlap (`2018-07-03`), which is correct. I guess there was an election, and Gianluca retained his position.

I have to fix the period and probably change it to INFO because this situation is quite common and usually is not an error. #306

**Pull request closed without merging**
