### PR TITLE
add odd derived schema target to makefile: make DEV-val-schema-ParlaMintODD

### PR DESCRIPTION
**Pull request by matyaskopp**

### CODE REVIEW

**Comment by TomazErjavec** [comment]
Thanks! But can't it be simply val-schema-odd?

**Comment by matyaskopp** [comment]
I can change it, but we have said that this is not meant for validation. The odd version is only for documentation.
But If you want to run all validations (ParlaMint, ParlaMint.odd and ParlaCLARIN), I can change it when you run `make val-schema`.

**Comment by TomazErjavec** [comment]
Well, it is meant for validation but parlamint odd validation. In an ideal world, we wouldn't even have the rng, just the odd.

Would it make sense to have the following validations, going from the general to specific:
val-parlaclarin, val-odd, val-rng, val-xslt. And then val-schema could just call val-parlaclarin, val-rng, val-xslt.

But maybe this is a silly idea that doesn't fit with the code.

**Comment by matyaskopp** [comment]
Currently:
`val-schema` calls:
- `val-schema-ParlaMint`
- `val-schema-ParlaCLARIN`

and when you want to do extended validation, you should call `check-links` and `check-content` (and `DEV-validate-particDesc`, which I will probably move under `check-content`)
+ validation of derived formats

I can add clearly named targets `validate` and `validate-XX`, which will run all required validations.

**Pull request merged**
