### PR TITLE
Data TR

### PR DESCRIPTION
**Pull request by coltekin**
This adds some parties to orientation and party .tsv files.

### CODE REVIEW

**Comment by coltekin** [comment]
Sorry for the confusion (earlier request ##410) this PR should now include the correct sample data.

**Comment by matyaskopp** [comment]
@coltekin, please reduce the size of your sample = remove derived files and then the hugest files
the files' size in total should be under 100MB in total

**Comment by coltekin** [comment]
I reduced the example files / sizes, fixed some bugs, and improved the structure in some places. I plan prepare the complete corpus using this version of the pipeline. Please let me know if there are any issues to be resolved.

Some of the warnings will disappear with the complete corpus (organizations with no members), but I plan to leave the warnings about open party membership as is now (as discussed in #368).

Do you prefer me to squash the commits in my fork and open another pull request? Otherwise, I guess, the older/large files will still be in the history.

**Comment by TomazErjavec** [comment]
> I reduced the example files / sizes, fixed some bugs, and improved the structure in some places. I plan prepare the complete corpus using this version of the pipeline. Please let me know if there are any issues to be resolved.

Looks good to me!

> Some of the warnings will disappear with the complete corpus (organizations with no members), but I plan to leave the warnings about open party membership as is now (as discussed in https://github.com/clarin-eric/ParlaMint/issues/368).

OK, something for 3.1 then.

> Do you prefer me to squash the commits in my fork and open another pull request? Otherwise, I guess, the older/large files will still be in the history.

Yes, squash would be nice indeed.

**Comment by coltekin** [comment]
Discarding this PR as agreed (I will open a new one).

**Pull request closed without merging**
