### PR TITLE
Data HU

### PR DESCRIPTION
**Pull request by matyaskopp**

### CODE REVIEW

**Comment by matyaskopp** [comment]
@lnnoemi, this pull request is from the correct branch in your repository to the correct branch of this repository.
There is no need to open other pull requests - it is automatically synced/updated with new data

**Comment by lnnoemi** [comment]
Ok, I think I get it (but I'm not sure).

So if I add some new data, and commit and push, then it will be
automatically synced in the remote repository?


And I keep getting messages like "Validate workflow run, Attempt #2", and
some messages about validating countries "Validate, Attempt #2 /
ValidateCountries (HU)". Could you help me with that?
n

**Comment by matyaskopp** [comment]
> So if I add some new data, and commit and push, then it will be
automatically synced in the remote repository?

No, data in this repository will not be affected.
This pull request will rerun a validation procedure.

> And I keep getting messages like "Validate workflow run, Attempt #2", and
some messages about validating countries "Validate, Attempt #2 /
ValidateCountries (HU)". Could you help me with that?

you can see error messages (for this run) here: 
https://github.com/clarin-eric/ParlaMint/actions/runs/3371571615/jobs/5595205882#step:4:22

**Comment by lnnoemi** [comment]
I'm sorry, but I have no idea what I am doing wrong. :) 
Could you please send me some screenshots? If I go to the data branch of my fork, set base:data-HU and compare:data, I can not do anything else but create a pull request there. :) 
contributing.md also says 'create a pull request' 

So if you could help me with some screenshots, I probably would not bother you again with my erroneous attempts to update the data :)

**Comment by matyaskopp** [comment]
> I'm sorry, but I have no idea what I am doing wrong. :)

do nothing, just update your data in [lnnoemi:data](https://github.com/lnnoemi/ParlaMint/tree/data) branch in your repository.

> Could you please send me some screenshots? If I go to the data branch of my fork, set base:data-HU and compare:data, I can not do anything else but create a pull request there. :)

oh, I probably understand what the issue is: 
You are trying to push data into `data-HU` branch, which is my testing branch - do not use it. Everybody is supposed to use `data` branch.

and you are pushing your data into main branch in our repository (this fixes it: https://github.com/lnnoemi/ParlaMint/pull/4)

You have to switch branches on your local copy in your computer
```bash
git checkout data # switching branch
git pull # loading newest data
```
and then you can add new data and push it into GitHub (to your fork https://github.com/lnnoemi/ParlaMint/tree/data)

**Comment by lnnoemi** [comment]
Ok, thanks.

So now are my data fine? Are my commits from this morning in the right
place?

n

**Comment by matyaskopp** [comment]
@lnnoemi, can you please update your repository with the current sample - the correct filenames?

**Comment by matyaskopp** [comment]
@lnnoemi,
I am ready to merge your pull request. But my recent changes made your data invalid (you will see once you merge this: https://github.com/lnnoemi/ParlaMint/pull/5)
- changed taxonomy filenames (suffix .ana)
- changed/added `xml:id`
- added `xml:lang`
---
There are two options to solve it:
 
1) I will merge your data into this repository and fix it

2) you will:
- merge this pull request https://github.com/lnnoemi/ParlaMint/pull/5
and then run this sequence of commands, which should fix it in your local copy:
```bash
# put taxonomies back into root file:
make composite-teiHeader-INPLACE-HU
# factorize taxonomies again:
make factorize-teiHeader-INPLACE-HU
# add new files into repository (taxonomies with suffix '.ana.xml')
git add Data/ParlaMint-ES-CT/ParlaMint-taxonomy-NER.ana.xml
git add Data/ParlaMint-ES-CT/ParlaMint-taxonomy-UD-SYN.ana.xml
# check if it is ok
git diff Data/ParlaMint-HU
# commit
git commit Data/ParlaMint-HU
```

Which option do you prefer?

**Comment by lnnoemi** [comment]
I think the first option is the safer one, so if you don't mind, I prefer that.

Does this mean that I can upload the whole corpus now to the link?

**Pull request merged**
