### PR TITLE
Data FR

### PR DESCRIPTION
**Pull request by matyaskopp**

### CODE REVIEW

**Comment by matyaskopp** [comment]
@gclux 
---
```
ERROR[18] : Missing implicated affiliation role 'member' in PA2150 affiliation [affiliation from="2017-06-27" ref="#PO730958" role="head"]
              [roleName xml:lang="fr"]président[/roleName]
              [roleName xml:lang="en"]President[/roleName]
            [/affiliation]
```
it is documented here: https://clarin-eric.github.io/ParlaMint/#sec-affiliation
> It should be noted that ParlaMint makes no assumptions on the interconnection between various roles, e.g. we do not assume that if somebody has a minister role in the government that they are also a member of the government. Therefore it is necessary to specify all the desired affiliations with their particular roles, e.g. both as minister and as member.
> ...
> - Leader of parliamentary group: affiliation/@role="head" & affiliation/@role="member" → org/@role="parliamentaryGroup" (cf. Section on [Political parties and parliamentary groups](https://clarin-eric.github.io/ParlaMint/#sec-parties))

---
```
ERROR[12] : Total number of organizations with government role: 66
```
We are expecting one government organization: "Gouvernement de la République française"
You have encoded one(or more) organization for each ministry, if you want to have ministry organization you can, but there is a different role `ministry`: https://clarin-eric.github.io/ParlaMint/#sec-orgs

**Comment by gclux** [comment]
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by matyaskopp** [comment]
@gclux 
> OK. I have updated the branch... What else?

Your sample is not valid, so you are supposed to fix errors.
https://github.com/clarin-eric/ParlaMint/actions/runs/3370641972/jobs/5591812071#step:4:38


> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

I will merge it once it passes the validation and my manual check.

**Comment by gclux** [comment]
@matyaskopp 
I see. I have a problem with this error message...
`ERROR[18] : Missing implicated affiliation role 'member' in ...`
This is also discussed in...
https://github.com/clarin-eric/ParlaMint/pull/424
But still unclear to me. I have read...
https://clarin-eric.github.io/ParlaMint/#sec-affiliation
After a few attempts, I conclude that for a minister we should have something like...
```
          <person xml:id="PA1872">
            <persName>
              <forename>Jean-Yves</forename>
              <surname>Le Drian</surname>
            </persName>
            <sex value="M" />
            <birth when="1947-06-30">
              <placeName>Lorient, Morbihan</placeName>
            </birth>
            <occupation xml:lang="fr">Inspecteur général de l'éducation nationale</occupation>
            <affiliation ref="#PO729976" from="2017-06-22" to="2020-07-06" role="head">
              <roleName xml:lang="fr">ministre</roleName>
              <roleName xml:lang="en">Minister</roleName>
            </affiliation>
            <affiliation role="member" ref="#PO729976" from="2017-06-22" to="2020-07-06" />
            <affiliation role="minister" ref="#ParlaMint-FR-GOV" from="2017-06-22" to="2020-07-06" />
            <affiliation role="member" ref="#ParlaMint-FR-GOV" from="2017-06-22" to="2020-07-06" />
          </person>

``` 
Correct?

**Comment by matyaskopp** [comment]
> But still unclear to me. I have read... https://clarin-eric.github.io/ParlaMint/#sec-affiliation After a few attempts, I conclude that for a minister we should have something like...
> 
> ```
>           <person xml:id="PA1872">
>             <persName>
>               <forename>Jean-Yves</forename>
>               <surname>Le Drian</surname>
>             </persName>
>             <sex value="M" />
>             <birth when="1947-06-30">
>               <placeName>Lorient, Morbihan</placeName>
>             </birth>
>             <occupation xml:lang="fr">Inspecteur général de l'éducation nationale</occupation>
>             <affiliation ref="#PO729976" from="2017-06-22" to="2020-07-06" role="head">
>               <roleName xml:lang="fr">ministre</roleName>
>               <roleName xml:lang="en">Minister</roleName>
>             </affiliation>
>             <affiliation role="member" ref="#PO729976" from="2017-06-22" to="2020-07-06" />
>             <affiliation role="minister" ref="#ParlaMint-FR-GOV" from="2017-06-22" to="2020-07-06" />
>             <affiliation role="member" ref="#ParlaMint-FR-GOV" from="2017-06-22" to="2020-07-06" />
>           </person>
> ```
> 
> Correct?

You don't use very informative ids, so it is difficult to say without context.

If the `#PO729976` refers to an organization with a `ministry` role, then it is correct (minister is a head of ministry).
But we don't insist on encoding ministry organizations. We just want a government organization where ministers should be affiliated with `minister` and `member` roles (you have it).

**Comment by gclux** [comment]
I think that now the validation is OK (just warnings).
However:
- the parliament organization is not the second one as it should be
- the sub-directory structure is not as we discussed yesterday
Question: is there a set of samples (pulled into my local repository) which could be used as a completed example? ... CZ?

**Comment by TomazErjavec** [comment]
It looks to like your sample is [too large](https://github.com/clarin-eric/ParlaMint/actions/runs/3550066121/jobs/5963106151), no? 

> Question: is there a set of samples (pulled into my local repository) which could be used as a completed example? ... CZ?

In [data branch](https://github.com/clarin-eric/ParlaMint/tree/data/Data). 
@matyaskopp, do you think that those that pass validation should merge into main?

**Comment by matyaskopp** [comment]
> @matyaskopp, do you think that those that pass validation should merge into main?

Currently, the data branch is more or less synced with the main.
@TomazErjavec I don't want to merge this(https://github.com/clarin-eric/ParlaMint/pull/483) pull request now because it contains big AT sample - create sample failed there because @hpreki provided sample without debate:
https://github.com/clarin-eric/ParlaMint/blob/9524de14e26ab3a3a4b324299ff876979b34146e/Data/ParlaMint-AT/ParlaMint-AT_1999-10-28-020-XX-NRSITZ-00183.ana.xml#L141-L145

**Comment by gclux** [comment]
Are you talking about the AT sample or the FR sample?
Should I reduce my sample to <100MB?

**Comment by TomazErjavec** [comment]
> Are you talking about the AT sample or the FR sample?

[FR](https://github.com/clarin-eric/ParlaMint/actions/runs/3550066121/jobs/5963106151)
 
> Should I reduce my sample to <100MB?

Yes pls.

**Comment by gclux** [comment]
OK. It should be ~85 MB now.

**Comment by matyaskopp** [comment]
@gclux 
you are missing prefix definition, so your sample is not passing the validation:
```
  Error: /home/runner/work/ParlaMint/ParlaMint/ParlaMint/Data/ParlaMint-FR/ParlaMint-FR.ana.xml:683:20: error: element "encodingDesc" incomplete; missing required element "listPrefixDef"
....
  Error: ERROR ParlaMint-FR_2017-09-25-E2001.ana: Extended pointer ud-syn:cop but no prefixDef for prefix ud-syn found!
```
see sample:
https://github.com/clarin-eric/ParlaMint/blob/9a575df59b3c886967c63f9c902a2881b2adedbd/Data/ParlaMint-CZ/ParlaMint-CZ.ana.xml#L130-L133

and you include files that are not in the repository:
```
 Error: ERROR: /home/runner/work/ParlaMint/ParlaMint/ParlaMint/Data/ParlaMint-FR/ParlaMint-FR.xml XIncluded file /home/runner/work/ParlaMint/ParlaMint/ParlaMint/Data/ParlaMint-FR/2017-18/ParlaMint-FR_2017-10-03-O1001.xml does not exist!
```
please remove these files from root files

**Comment by matyaskopp** [comment]
> 1. /home/glux/Work/GitHub/ParlaMint/Data/ParlaMint-FR/2017-18-ana/ParlaMint-FR_2017-09-25-E2002.ana.xml:88:56: error: element "s" not allowed here; expected data
>    `<s>` is not allowed within `<head>` ?

`<head>` is something like `<note>` so no annotated text is expected here.



> 2\. INFO: Link checking for ParlaMint-FR_2017-09-25-E2002.ana.xml
>     ERROR ParlaMint-FR_2017-09-25-E2002.ana: ERROR: Can't find local id for link/@ana="ud-syn:expl_pv"
>     We don't have the lines of these errors, so difficult to understand... The @xml:ids are apparently always defined.

This particular error says that you are missing `expl_pv` in your `UD-SYN` taxonomy, so you should add:
https://github.com/clarin-eric/ParlaMint/blob/9a575df59b3c886967c63f9c902a2881b2adedbd/Data/Taxonomies/ParlaMint-taxonomy-UD-SYN.ana.xml#L752-L754

**Pull request merged**
