### PR TITLE
Data IS

### PR DESCRIPTION
**Pull request by starkadur**

### CODE REVIEW

**Comment by starkadur** [comment]
I was told the last time that even though ParlaMint-IS passed validation it had some issues. I don't remember what it was and can't find any email or gitHub issue mentioning it. Could you let me know if everything is ok with this? (I know that I have to remove the "political party" 'Utan flokka / non aligned' from listOrg -noticed it too late).

**Comment by matyaskopp** [comment]
@starkadur can you please run:
```bash
make factorize-teiHeader-INPLACE-IS
```
in your repository and commit changes?

it will factorize `teiHeader` in-place and the sample of result can be seen in CZ directory:
https://github.com/clarin-eric/ParlaMint/tree/data/Data/ParlaMint-CZ
- taxonomies, listPerson and listOrg are in separate files

**Comment by matyaskopp** [comment]
> @starkadur can you please run:
> 
> ```shell
> make factorize-teiHeader-INPLACE-IS
> ```
> 
> in your repository and commit changes?
> 
> it will factorize `teiHeader` in-place and the sample of result can be seen in CZ directory: https://github.com/clarin-eric/ParlaMint/tree/data/Data/ParlaMint-CZ
> 
> * taxonomies, listPerson and listOrg are in separate files

May I ask you to factorize your teiHeader?
I really want to merge your data but I want to have factorized teiHeader first

**Comment by starkadur** [comment]
Hi Matyas.

I have factorized the TeiHeader and created a pull request.

Let me know (when you can) what my next steps are in order to deliver the
whole ParlaMint-iS.


mið., 2. nóv. 2022 kl. 16:53 skrifaði Matyáš Kopp ***@***.***

**Comment by matyaskopp** [comment]
@starkadur thanks, merging it into data

**Pull request merged**
