### PR TITLE
Data-ES-CT_25_01_2023

### PR DESCRIPTION
**Pull request by rjzevallos**

### CODE REVIEW

**Comment by rjzevallos** [comment]
I have just updated this branch with the last observations, can you tell me if everything is correct? Thanks for your support

**Comment by matyaskopp** [comment]
> I have just updated this branch with the last observations, can you tell me if everything is correct? Thanks for your support

Yes, I think that this is an acceptable format. But you can still improve it:
https://github.com/clarin-eric/ParlaMint/issues/491#issuecomment-1352666426

> ## mention the proper source in bibl
> -  proper source of component file in bibl
> You can add the proper source of a file into the bibl element in this place: https://github.com/IULATERM-TRL-UPF/ParlaMint/blob/960d8fed8178b5d9b1f2659c60630d2bf2235e02/Data/ParlaMint-ES-CT/ParlaMint-ES-CT_2018-01-17-0101.xml#L58
> ```XML
> <idno type="URI" subtype="parliament">https://www.parlament.cat/document/dspcp/239595.pdf</idno>
> ```

I am not insisting on that, but I believe that the authors of the corpus should insist on citing the source.
So, leaving it up to you.

@matyaskopp should solve this #561 
then you will sync it with your repository 
and finally I can merge your sample into this repository

**Comment by rjzevallos** [comment]
Done!

**Comment by rjzevallos** [comment]
We'v fixed warning issues

**Comment by rjzevallos** [comment]
Fixed errors

**Pull request merged**
