### PR TITLE
Data ES-CT

### PR DESCRIPTION
**Pull request by marilinapisani**
Added samples to folder

### CODE REVIEW

**Comment by matyaskopp** [comment]
@marilinapisani, thanks for the pull request. 
I have changed the target branch to 'data'. You are supposed to make pull requests into the data branch.

If you need any explanation of errors in the output: https://github.com/clarin-eric/ParlaMint/runs/7127336080?check_suite_focus=true#step:4:27
don't hesitate to ask. The questions can help me to make output messages better.

**Comment by marilinapisani** [comment]
@matyaskopp, thanks for your comment. For the next pull, where am I supposed to change the target branch? I followed the instructions in the Contributing file. Sorry if this is a basic question, this is my first commit. 

Regarding the error logs, I am reviewing them and so far they seem clear to me.

**Comment by marilinapisani** [comment]
perfect!

**Comment by marilinapisani** [comment]
@matyaskopp I do have doubts regarding this error message: "New document or paragraph starts when the last token of the previous sentence says SpaceAfter=No."

**Comment by matyaskopp** [comment]
> @matyaskopp I do have doubts regarding this error message: "New document or paragraph starts when the last token of the previous sentence says SpaceAfter=No." Could you kindly clarify it for me? Thanks!

This error is reported by this tool https://github.com/UniversalDependencies/tools/blob/master/validate.py. It uses the wrong id in the report: 

https://github.com/clarin-eric/ParlaMint/runs/7127336080?check_suite_focus=true#step:4:189
```
[Line 217 Sent ParlaMint-ES-CT_2015-11-09.u.1.4.1]: [L2 Metadata spaceafter-newdocpar] New document or paragraph starts when the last token of the previous sentence says SpaceAfter=No.
```

the issue is in the following sentence (`ParlaMint-ES-CT_2015-11-09.u.1.4.2`):
```XML
    <pc ana="mte:PUNCT" join="right" msd="UPosTag=PUNCT" xml:id="ParlaMint-ES-CT_2015-11-09.u.1.4.2.92">.</pc>
    <linkGrp targFunc="head argument" type="UD-SYN"> ... </lingGrp>
    </s>
</seg>
```

The last token in the sentence(`ParlaMint-ES-CT_2015-11-09.u.1.4.2.92`) contains `join="right"` which is not allowed because the paragraphs should be separated.

All last paragraph tokens in your data seem to contain `join="right"`.

**Comment by marilinapisani** [comment]
That's very helpful, thanks!

**Comment by TomazErjavec** [comment]
Can this pull request be closed (without merging)?

**Pull request closed without merging**
