### PR TITLE
Data AT

### PR DESCRIPTION
**Pull request by hpreki**
new sample for ParlaMint-3.1: 

* updated Metadata
* removed sample protocol XVII-00159  and replaced it with XVII-00178 (i.e. the current most recent protocol  in ParlaMint-AT)

### CODE REVIEW

**Comment by hpreki** [comment]
the 1st pull request failed because 
* the new `@role` `federatedState` is not yet part of the Schema in `data` branch - only in the branch `documentation`
* `add-common-content` now adds a new subcorpus-type `#war` which is not yet part of my `ParlaMint-taxonomy-subcorpus.xml`
@matyaskopp  is there any action required from my side? I suppose _you_ would  update the Schema in the `data` branch? But I suppose _I_ should take care of `ParlaMint-taxonomy-subcorpus.xml`?

**Comment by TomazErjavec** [comment]
This is a very old pull request - is it still relevant, or can we close it?

**Comment by hpreki** [comment]
@TomazErjavec is there a chance we can still finish this pull request?  Especially I would like to see `Data/ParlaMint-AT/ParlaMint-AT-listPerson.xml` be up to date in the repo. (The current version in the repo is outdated and would not validate. A correct(ed) version of listPerson was handed in to you as part of our submission for ParlaMint-3.1, but this was via a Web-share and never made it into the git-repo.)

**Comment by TomazErjavec** [comment]
> @TomazErjavec is there a chance we can still finish this pull request? 

I don't think we can, because the repo structure has changed in the meantime (we don't have Data/ anymore, rather, Samples/). But @matyaskopp is more in tune with the git maintenance.
In any case, your files will make it to GitHub, but now with everybody sending fixes and translations, it is a bit chaotic.

**Comment by matyaskopp** [comment]
@hpreki 

there is an isssue that your repo is out of date and the `Data` folder has been renamed to `Sample`
I think this procedure will work:

1. backup your sample files on your local host:
```bash
cp -r Data/ParlaMint-AT ParlaMint-AT-BACKUP
```
2. remove the files from repository:
```bash
git rm Data/ParlaMint-AT/ParlaMint-AT-listOrg.xml \
Data/ParlaMint-AT/ParlaMint-AT-listPerson.xml \
Data/ParlaMint-AT/ParlaMint-AT.ana.xml \
Data/ParlaMint-AT/ParlaMint-AT.xml \
Data/ParlaMint-AT/ParlaMint-AT_2005-03-31-022-XXII-NRSITZ-00100.ana.xml \
Data/ParlaMint-AT/ParlaMint-AT_2005-03-31-022-XXII-NRSITZ-00100.xml \
Data/ParlaMint-AT/ParlaMint-AT_2014-09-24-025-XXV-NRSITZ-00042.ana.xml \
Data/ParlaMint-AT/ParlaMint-AT_2014-09-24-025-XXV-NRSITZ-00042.xml \
Data/ParlaMint-AT/ParlaMint-taxonomy-NER.ana.xml \
Data/ParlaMint-AT/ParlaMint-taxonomy-speaker_types.xml \
Data/ParlaMint-AT/ParlaMint-taxonomy-subcorpus.xml 
```
3. commit and push
```bash
git commit -m "remove AT files" Data/ParlaMint-AT
git push
```
4. sync your fork https://github.com/hpreki/ParlaMint/compare/data...clarin-eric:ParlaMint:data
5. add files to correct folder (`Sample/PArlaMint-AT`)

**Comment by hpreki** [comment]
@matyaskopp thanks a lot for your detailed "cooking recipe"! I followed your advice, and the pull request looks much better to me right now: it seems to me that it passed all checks.

**Pull request merged**
