### PR TITLE
DK  add common content

### PR DESCRIPTION
**Pull request by BartJongejan**

### CODE REVIEW

**Comment by BartJongejan** [comment]
I do not know what to do about the failing "ValidateCountries (DK) (pull_request)". Is it caused by a 10 minute time out? Wh(o|at) is to blame for that?

**Comment by TomazErjavec** [comment]
@BartJongejan , I re-ran the script again with debugging on (can this be a problem for ordinary use, @matyaskopp?) and https://github.com/clarin-eric/ParlaMint/actions/runs/2999165493 does give some errors in the data. I hope the URL travels, if not, here is a copy:

```
10 errors and 2 notices
ValidateCountries (DK)
ERROR[10] ParlaMint-DK: government-role organisation without affiliation: #ParlaMint-DK-GOV
ValidateCountries (DK)
Error at char 92 in expression in xsl:value-of/@select on line 590 column 228 of validate-parlamint-particDesc.xsl:
ValidateCountries (DK)
ERROR ParlaMint-DK: ERROR: Can't find local id for affiliation/@ana="#FT.15 #FT16"
ValidateCountries (DK)
ERROR ParlaMint-DK: ERROR: Can't find local id for affiliation/@ana="#FT14 #FT.15 #FT.16 #FT.19"
ValidateCountries (DK)
ERROR ParlaMint-DK: ERROR: Can't find local id for affiliation/@ana="#FT14 #FT.15 #FT.16 #FT.19"
ValidateCountries (DK)
ERROR ParlaMint-DK: ERROR: Can't find local id for affiliation/@ana="#FT14 #FT.15 #FT.16 #FT.19"
ValidateCountries (DK)
ERROR ParlaMint-DK: ERROR: Can't find local id for affiliation/@ana="#FT14 #FT.15 #FT.16 #FT.19"
ValidateCountries (DK)
ERROR ParlaMint-DK: ERROR: Can't find local id for affiliation/@ana="#FT16"
ValidateCountries (DK)
ERROR ParlaMint-DK: Strange pointer 'FT.15'
ValidateCountries (DK)
ERROR ParlaMint-DK: Strange pointer 'FT.16'
```

**Comment by matyaskopp** [comment]
> can this be a problem for ordinary use, @matyaskopp?

no, it is not a big problem - only the failing message is not informative (the rest of the validation fails at this point):
```
  Error: Error at char 92 in expression in xsl:value-of/@select on line 590 column 228 of validate-parlamint-particDesc.xsl:
    FORG0001  Invalid dateTime value "2017-09" (Too short)
  at function mk:get_org_from on line 587 column 0 of validate-parlamint-particDesc.xsl:
       invoked by function call at file:/home/runner/work/ParlaMint/ParlaMint/ParlaMint/Scripts/validate-parlamint-particDesc.xsl#38
    In template rule with match="tei:affiliation" on line 13 of validate-parlamint-particDesc.xsl
       invoked by built-in template rule (text-only)
    In template rule with match="text()" on line 429 of validate-parlamint-particDesc.xsl
       invoked by built-in template rule (text-only)
    In template rule with match="text()" on line 429 of validate-parlamint-particDesc.xsl
       invoked by xsl:apply-templates at file:/home/runner/work/ParlaMint/ParlaMint/ParlaMint/Scripts/validate-parlamint-particDesc.xsl#316
    In template rule with match="tei:particDesc" on line 315 of validate-parlamint-particDesc.xsl
       invoked by built-in template rule (text-only)
    In template rule with match="text()" on line 429 of validate-parlamint-particDesc.xsl
       invoked by built-in template rule (text-only)
    In template rule with match="text()" on line 429 of validate-parlamint-particDesc.xsl
       invoked by built-in template rule (text-only)
       invoked by built-in template rule (text-only)
  Invalid dateTime value "2017-09" (Too short)`
```

@BartJongejan, can you see the detailed log? https://github.com/clarin-eric/ParlaMint/runs/8204061831?check_suite_focus=true#step:4:80

**Comment by BartJongejan** [comment]
So, DK data can currently be merged, right ?

**Comment by BartJongejan** [comment]
COMMENT TO ORIENTATION-DK:
- PM_ID were added to SD (S) and v (V)
- Parties irrelevant to current corpus were removed
- New party FG was added
Please inform us if we need to add this information to the root file or it will be done automatically.

**Comment by TomazErjavec** [comment]
> COMMENT TO ORIENTATION-DK: 
>     * PM_ID were added to SD (S) and v (V)
>     * New party FG was added
>     * Parties irrelevant to current corpus were removed
No need for the last step, in fact, it is better to leave them there, maybe they come in useful at some further point.

@katjameden, @jureskubic, could you pls. check that the TSV taken was in fact the correct one (as I know you are still working on some of them) and that the changes make sense? If so, maybe you can edit your copy to be in line with @BartJongejan's.

> Please inform us if we need to add this information to the root file or it will be done automatically.

The idea is to do this autmatically, but you can surely try to do it yourself, at least as a test. The Makefile target is https://github.com/clarin-eric/ParlaMint/blob/deb59f1f98701be4d96d34de766a3aa77fef9d4b/Makefile#L496-L517

However, the updated schema that validates the XML with added orientation was made in the documentation branch, and I am not sure if it has been merge yet into main.

**Comment by jureskubic** [comment]
@TomazErjavec I just did the fetch origin on github desktop and checked the DK TSV and it is not the final one. I have the final one on my PC since I was still working on it. Therefore, data in both TSVs are different. I also cannot see the abovementioned corrections in the DK file.

**Comment by TomazErjavec** [comment]
> @TomazErjavec I just did the fetch origin on github desktop and checked the DK TSV and it is not the final one. I have the final one on my PC since I was still working on it. Therefore, data in both TSVs are different.

OK, @jureskubic, so it would be great if you could take @BartJongejan TSV, and introduce his (sensible) changes into your TSV.

> I also cannot see the abovementioned corrections in the DK file.

This is because it has not been merged into CLARIN ERIC ParlaMint repo - you need to take it directly from @BartJongejan TSV, i.e. https://github.com/kuhumcst/ParlaMint/blob/data/Data/Metadata/Parties/Orientation-DK.tsv

**Comment by matyaskopp** [comment]
@jureskubic @BartJongejan, we need to solve a conflict in this issue, so it would be possible to sync [kuhumcst:data](https://github.com/kuhumcst/ParlaMint/tree/data) branch with [clarin-eric:data](https://github.com/clarin-eric/ParlaMint/tree/data) and see if the last validation updates did not discover any new issue

**Comment by TomazErjavec** [comment]
> @jureskubic @BartJongejan, we need to solve a conflict in this issue, so it would be possible to sync [kuhumcst:data](https://github.com/kuhumcst/ParlaMint/tree/data) branch with [clarin-eric:data](https://github.com/clarin-eric/ParlaMint/tree/data) and see if the last validation updates did not discover any new issue

In the meantime @jureskubic has fixed some errors in @BartJongejan's TSV and we have put the new DK TSV in the repo. 

So, could @BartJongejan pls take [this TSV](https://github.com/clarin-eric/ParlaMint/blob/main/Data/Metadata/Parties/Orientation-DK.tsv) and just put it in his repo, and the problem will be solved.

There is one party we didn't find info for, namely UFG. If @BartJongejan could afterwards help @jureskubic with it, it would be great. Hm, actually, I just noticed another error: Line 55, third column should be "V" and not "v".

**Pull request closed without merging**
