### PR TITLE
PT data

### PR DESCRIPTION
**Pull request by cluljoseaires**
PT data

### CODE REVIEW

**Comment by matyaskopp** [comment]
https://github.com/clarin-eric/ParlaMint/issues/331#issuecomment-1236962963 :
> the total size of your corpus is 5306 MB: https://github.com/clarin-eric/ParlaMint/runs/8178813844?check_suite_focus=true#step:4:33
> 
> You are allowed to upload only 100 MB. Please remove some files (to reduce the sample to approximately 80MB to be sure that it passes the limit) from git and xincludes from root XML files.

**Comment by matyaskopp** [comment]
the limitation calculations are made with this script:
https://github.com/clarin-eric/ParlaMint/blob/1c681c952eeeb534b05bac58c7f1263dd83a9a50/.github/actions/ParlaMintStatus/status.sh#L13-L19

You are not allowed to upload gigabytes of files:
- it takes a while to compute all validations
- validation is run on every data update
- people usually don't need your full corpus on a local repo copy (I do not even have enough space for all full corpora on my laptop)

**Comment by cluljoseaires** [comment]
Thank you very much.

However, I hope that you mean we are only allowed to upload 100MB «at a time», because I need all those files to cover the required period.

If such is the case, I guess the solution will be to remove all files except around 70MB (just in case), commit, request a pull, and keep adding around 70MB of files, along with the corresponding commits and pull requests, until all of them are validated.

By the way, in the iterative process above, if the files with the xincludes could keep all the references, even for the files that will be present in the following iterations, would greatly simplify my job.

You should get another laptop... :P ;) :)

**Comment by TomazErjavec** [comment]
@cluljoseaires, GitHub is only meant for uploading samples, not the compete corpus. The idea is to check everyting on a sample, and, when that is ok, process the complete corpus localy.  Given that we don't even have samples for most of the corpora yet, we haven't really discussed how to share the complete corpora.

**Comment by TomazErjavec** [comment]
> Sorry for insisting but, if I understand correctly, I can then choose any 70MB of files as a sample, and you only need one sample.

Exactly.

> I have already done the verification locally for all the files and there were no errors.

Aha, this is very good news! So, let us wait that you sample is merged without errors, and then we can discuss what to do with you complete corpus . You will be the first one to have it.

**Comment by matyaskopp** [comment]
It seems that PT corpus have valid structure according to ParlaMint recommendations:
```bash
make validate-parlamint-PT
```

but a validation of derived format fails, use this command to convert and then validate:
```bash
make conllu-PT
```
this validation starts here in an action log: https://github.com/clarin-eric/ParlaMint/runs/8194476525?check_suite_focus=true#step:4:141

**Comment by cluljoseaires** [comment]
Following your suggestion to run 'make conllu-PT', I came across the issue of "Scripts/tools/validate.py" missing.

This reminded me that such issue also arose when running 'make check-prereq', but since I was just running (without issues) make val-schema-PT, make check-links-PT, make check-content-PT and make validate-parlamint-PT, which seemed to me the most obvious options and did not depend on the given script, I figured it might not be important, but now I guess it matters.

I am not fluent in git, but I have searched for the file in previous versions of the repository but I have not been able to find it. The closest I can find is "TEI/validate.pl", but not only it is perl instead of python, it does not seem to take the same arguments, so I would say they are not related.

All things considered, I also took the opportunity to run the remaining rules with the results below.

make text-PT -> no issues, but has to be run before chars-PT, even though the rule comes after in Makefile
make chars-PT -> no issues, but depends on text-PT, as pointed out above
make meta-PT -> no issues
make vertana-PT -> no issues
make conllu-PT -> Scripts/tools/validate.py missing, as pointed out earlier
make add-common-content-PT -> fatal bad country and several other issues

Hope this helps you help me.

**Comment by matyaskopp** [comment]
the issue is that you don't have installed prerequisites, so `make check-prereq` fails.
Agree that `make check-prereq` should be more informative. The information you search is in `make` command without arguments:
```
replace XX with country code or run target without -XX to process all countries: 
	 AT BE BG CZ DK EE ES ES-CT ES-GA ES-PV FI FR GB GR HR HU IS IT LT LV NL NO PL PT RO SE SI TR BA RS
 
VARIABLES:
Variable VAR with value 'value' can be set when calling target TARGET in  Makefile: make VAR=value TARGET
PARLIAMENTS        Space separated list of parliaments codes.
DATADIR            Folder with country corpus folders. Default value is 'Data'.
WORKINGDIR         In this folder will be stored temporary files. Default value is 'DataTMP'.
CORPUSDIR_SUFFIX   This value is appended to corpus folder so corpus directory name shouldn't be prefix
                   of corpus root file. E.g. setting CORPUSDIR_SUFFIX=.TEI allow running targets on content
                   of ParlaMint-XX.TEI folder that contains corresponding ParlaMint-XX(.ana).xml files.
                   Default value is ''.
TARGETS:
Setup                          
check-prereq              test if prerequisities are installed, more about installing prerequisities in CONTRIBUTING.md file
...
```
-> the installation process is described in [CONTRIBUTING.md](https://github.com/clarin-eric/ParlaMint/blob/main/CONTRIBUTING.md#install-prerequisites)

**Comment by cluljoseaires** [comment]
I still did not take care of the reported bug issues, but I would like to confirm if I can trust myself with the validations once I am done fixing them.

**Comment by cluljoseaires** [comment]
I just realized the tests have passed. I will now proceed to fixing the remaining issues pointed out in your observations.

**Comment by cluljoseaires** [comment]
As a side note, once I saw the tests had passed, I thought I could/should close the pull request, only to realize the "passed tests status" was no longer shown. I then decided to reopen the pull request and the tests seemed to take longer, making me fear I had broken something. Fortunately everything seems fine now, but here is the note.

**Comment by matyaskopp** [comment]
@cluljoseaires I am labelling it with **bug** label to avoid accidental merging.

Can you please make one commit with formatted XML files - it would be easier to follow changes (currently, you have 2-line XML root files)

**Comment by cluljoseaires** [comment]
By all means. Here are the formatted files, as asked. The files are generated automatically, so I will try to remember formatting them every time I commit. In any case, feel free to warn me.

**Comment by cluljoseaires** [comment]
As mentioned in the commit message I have addressed your observations and I know it could still require some adjustments but I believe the information needed is there.

**Comment by matyaskopp** [comment]
> As mentioned in the commit message I have addressed your observations and I know it could still require some adjustments but I believe the information needed is there.

@cluljoseaires,  thanks. I will take a look soon.

**Comment by cluljoseaires** [comment]
I fixed an issue with the minister roles and started issue #339 for some doubts I came up with in relation to some tags.

**Comment by cluljoseaires** [comment]
I took care of your last comments and I guess the taxonomies are now acceptable.

**Comment by matyaskopp** [comment]
@cluljoseaires  
please:
- sync your data branch with clarin-eric/ParlaMint/data
- can you run:
```bash
make factorize-teiHeader-INPLACE-PT
```
in your repository and commit changes?

it will factorize `teiHeader` in-place and the sample of result can be seen in CZ directory:
https://github.com/clarin-eric/ParlaMint/tree/data/Data/ParlaMint-CZ
- taxonomies, listPerson and listOrg are in separate files

**Comment by matyaskopp** [comment]
@TomazErjavec 
I have no idea why it previously passed and now it is failing: https://github.com/clarin-eric/ParlaMint/actions/runs/3330914774/jobs/5510033513#step:4:181

It seems that the information on coalition and opposition is missing. but it was not present in previous commits, and nothing happened.

**Comment by cluljoseaires** [comment]
Thank you so much, but do not worry. These things can be annoying but I managed to understand what happened. I do have the information required, I just did a tiny test manually and confirmed it. Once I update the scripts I will do another pull request as soon as possible. Again, thank you very much. ;)

**Comment by matyaskopp** [comment]
> Thank you so much, but do not worry. These things can be annoying but I managed to understand what happened. I do have the information required, I just did a tiny test manually and confirmed it. Once I update the scripts I will do another pull request as soon as possible. Again, thank you very much. ;)

@cluljoseaires, great to hear that.


@TomazErjavec,
But still, I think that 
https://github.com/clarin-eric/ParlaMint/blob/4daa373fa896df175261182c9d255f4c42876f33/Scripts/parlamint-lib.xsl#L296-L297
should return empty text in this situation
https://github.com/clarin-eric/ParlaMint/blob/4daa373fa896df175261182c9d255f4c42876f33/Scripts/parlamint-lib.xsl#L302-L304

to avoid this terrible  message:
```
  Error: ERROR: coalition / opposition info found in corpus
  Error: Type error on line 302 column 59 of parlamint-lib.xsl:
    XTTE0780  An empty sequence is not allowed as the result of a call to et:party-status#1
  at function et:party-status on line 297 column 0 of parlamint-lib.xsl:
       invoked by function call at file:/home/runner/work/ParlaMint/ParlaMint/ParlaMint/Scripts/parlamint2meta.xsl#103
    In template rule with match="tei:u" on line 65 of parlamint2meta.xsl
       invoked by xsl:apply-templates at file:/home/runner/work/ParlaMint/ParlaMint/ParlaMint/Scripts/parlamint2meta.xsl#62
    In template rule with match="tei:TEI" on line 40 of parlamint2meta.xsl
       invoked by built-in template rule (text-only)
  An empty sequence is not allowed as the result of a call to et:party-status#1
  parallel: This job failed:
  java -jar /usr/share/java/saxon.jar meta=/home/runner/work/ParlaMint/ParlaMint/ParlaMint/Data/ParlaMint-PT/ParlaMint-PT.xml -xsl:/home/runner/work/ParlaMint/ParlaMint/ParlaMint/Scripts/parlamint2meta.xsl /home/runner/work/ParlaMint/ParlaMint/ParlaMint/Data/ParlaMint-PT/ParlaMint-PT_darl12sl04n039-16-01-2015.xml > /home/runner/work/ParlaMint/ParlaMint/ParlaMint/SAMPLE/PT/ParlaMint-PT_darl12sl04n039-16-01-2015-meta.tsv
```

**Comment by TomazErjavec** [comment]
OK, @cluljoseaires, I won't worry too much. However, I do note that there is an error in the error message. It now says
```
ERROR: coalition / opposition info found in corpus
```
but should say 
```
ERROR: no coalition / opposition info found in corpus
```

There is also another meta-errors, i.e. the comment at the start of the function say `Output coalition/opposition/- of the speaker's party when speaking` but the script actually returns the empty string in case the party is not either coalition or opposition (which shouldn't actually happen). I will correct this in devel now.

But I also have no idea why it worked previously, esp. if this info was not present, as it is a required info, and it is ok to throw an error message if missing.

**Comment by TomazErjavec** [comment]
> But still, I think that et:party-status should return empty text in this situation

Indeed it should, and hopefully does now in [b7195d2](https://github.com/clarin-eric/ParlaMint/commit/b7195d2603f8a9840b2509a0236797cb83eac371).

**Comment by matyaskopp** [comment]
@cluljoseaires, can you sync a data branch again without updating your data - it should now produce a better error outpus

**Comment by cluljoseaires** [comment]
Here is the branch sync without updating the data as requested.

**Comment by cluljoseaires** [comment]
I managed to fix the missing issues.

**Comment by matyaskopp** [comment]
@cluljoseaires 
can you please rename component files according to the recommendations: [2.3. File names and directory structure](https://clarin-eric.github.io/ParlaMint/#sec-files)
 - keep the flattened directory structure
 - related to #428

**Comment by cluljoseaires** [comment]
I am not sure how flat the directory structure it should be since there is a subdirectory for each year...

**Comment by matyaskopp** [comment]
there is a subdirectory for a year in the release, but in the GitHub sample we do not have any subdirectories.
So you should just rename files into this format: `ParlaMint-PT_YYYY-MM-DD.....`

**Comment by cluljoseaires** [comment]
I am sorry for the confusion, but I have sent you and @TomazErjavec a message following the [submitting the completed corpora](https://github.com/clarin-eric/ParlaMint/blob/main/CONTRIBUTING.md#submitting-the-completed-corpora) steps, to which he replied, including you as a recipient, the following, among other things:

First thing I notice is the directory structure and filenames.
You should have subdirectories by year, and the filenames should be like
2015/ParlaMint-PT_2015-01-07-darl12sl04n034.ana.xml
rather than
./ParlaMint-PT_darl12sl04n034-07-01-2015.ana.xml

I have already fixed the filename as you mentioned in your previous comment, but the "flattening" has left me confused because that seemed very specific in the message, so I hope this can help you help me figure out what to do... :P

**Comment by matyaskopp** [comment]
I have highlighted the flattening because there is a difference between a distribution

From documentation:
> **For distribution the complete XML corpus** should be stored in a directory that has the same name prefix as the corpus root file. The directory then contains the corpus root file and its metadata files, while the corpus components should be in subdirectories, one per year...

and samples on GitHub, where we expect all files in the same folder without subfolders.

I had asked you to reupload a GitHub sample because the filenames are not valid, and I missed this when I was merging it into the data branch.

**Comment by cluljoseaires** [comment]
I am sorry. So you need a new fixed sample. Sure. I though we where over that because your comment seemed to me like a reply from my message today with the full corpus. :P

**Pull request merged**
